include(FetchContent)
find_package(OpenGL REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
find_package(GLEW REQUIRED)
find_package(Freetype REQUIRED)
find_package(nlohmann_json 3.11 QUIET)
if(NOT nlohmann_json_FOUND)
    FetchContent_Declare(nlohmann_json URL https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_MakeAvailable(nlohmann_json)
endif()
if(EXISTS "${PROJECT_SOURCE_DIR}/third_party/stb/stb_image.h")
    set(STB_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/third_party/stb")
else()
    FetchContent_Declare(stb URL https://github.com/nothings/stb/archive/refs/heads/master.zip DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_GetProperties(stb)
    if(NOT stb_POPULATED)
        FetchContent_Populate(stb)
    endif()
    set(STB_INCLUDE_DIR "${stb_SOURCE_DIR}")
endif()
if(EXISTS "${PROJECT_SOURCE_DIR}/third_party/miniaudio/miniaudio.h")
    set(MINIAUDIO_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/third_party/miniaudio")
else()
    FetchContent_Declare(miniaudio URL https://github.com/mackron/miniaudio/archive/refs/tags/0.11.22.tar.gz DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_GetProperties(miniaudio)
    if(NOT miniaudio_POPULATED)
        FetchContent_Populate(miniaudio)
    endif()
    set(MINIAUDIO_INCLUDE_DIR "${miniaudio_SOURCE_DIR}")
endif()
if(TARGET glfw)
    set(GEMEDEV_GLFW_TARGET glfw)
elseif(TARGET glfw3::glfw)
    set(GEMEDEV_GLFW_TARGET glfw3::glfw)
else()
    message(FATAL_ERROR "No GLFW CMake target was found")
endif()
